// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC8B7xTKa1Dxgf4WC0_9dRqYx8GbPxXfE',
    appId: '1:1097351485542:web:a983eddef33db9b816b5a7',
    messagingSenderId: '1097351485542',
    projectId: 'jspm-connect',
    authDomain: 'jspm-connect.firebaseapp.com',
    storageBucket: 'jspm-connect.firebasestorage.app',
    measurementId: 'G-9GTVFCJY8J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAArRbqIpKBsImyI78QIr3LwisBSZI99R8',
    appId: '1:1097351485542:android:a7a9d5ebc1bdd31616b5a7',
    messagingSenderId: '1097351485542',
    projectId: 'jspm-connect',
    storageBucket: 'jspm-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxvMGJTWeNSqTJiLQHWAY4IaGlOz51Ico',
    appId: '1:1097351485542:ios:e92d80af69be10d216b5a7',
    messagingSenderId: '1097351485542',
    projectId: 'jspm-connect',
    storageBucket: 'jspm-connect.firebasestorage.app',
    iosBundleId: 'com.example.jspmConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxvMGJTWeNSqTJiLQHWAY4IaGlOz51Ico',
    appId: '1:1097351485542:ios:e92d80af69be10d216b5a7',
    messagingSenderId: '1097351485542',
    projectId: 'jspm-connect',
    storageBucket: 'jspm-connect.firebasestorage.app',
    iosBundleId: 'com.example.jspmConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC8B7xTKa1Dxgf4WC0_9dRqYx8GbPxXfE',
    appId: '1:1097351485542:web:427b98e94bff7c2616b5a7',
    messagingSenderId: '1097351485542',
    projectId: 'jspm-connect',
    authDomain: 'jspm-connect.firebaseapp.com',
    storageBucket: 'jspm-connect.firebasestorage.app',
    measurementId: 'G-9GCBZBP0TB',
  );
}
